import jsPDF from 'jspdf';
import { ScanResult } from './pentestTools';
import { format } from 'date-fns';

export function exportToPDF(scan: ScanResult): void {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  const margin = 20;
  const contentWidth = pageWidth - margin * 2;
  let yPos = margin;

  // Header
  doc.setFillColor(17, 24, 39);
  doc.rect(0, 0, pageWidth, 40, 'F');
  
  doc.setTextColor(0, 255, 150);
  doc.setFontSize(24);
  doc.setFont('helvetica', 'bold');
  doc.text('PENTEST REPORT', margin, 28);
  
  yPos = 55;

  // Scan Info Box
  doc.setFillColor(31, 41, 55);
  doc.roundedRect(margin, yPos, contentWidth, 50, 3, 3, 'F');
  
  doc.setTextColor(156, 163, 175);
  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  
  doc.text('Tool:', margin + 10, yPos + 15);
  doc.text('Target:', margin + 10, yPos + 28);
  doc.text('Date:', margin + 10, yPos + 41);
  
  doc.setTextColor(255, 255, 255);
  doc.text(scan.toolName, margin + 50, yPos + 15);
  doc.text(scan.target, margin + 50, yPos + 28);
  doc.text(format(new Date(scan.timestamp), 'MMMM d, yyyy HH:mm:ss'), margin + 50, yPos + 41);
  
  // Status badge
  const statusColor = scan.status === 'completed' ? [0, 255, 150] : 
                      scan.status === 'error' ? [255, 100, 100] : [255, 200, 0];
  doc.setTextColor(statusColor[0], statusColor[1], statusColor[2]);
  doc.text(scan.status.toUpperCase(), pageWidth - margin - 30, yPos + 15);
  
  yPos += 65;

  // Command Section
  doc.setTextColor(0, 255, 150);
  doc.setFontSize(12);
  doc.setFont('helvetica', 'bold');
  doc.text('EXECUTED COMMAND', margin, yPos);
  
  yPos += 10;
  
  doc.setFillColor(31, 41, 55);
  const cmdLines = doc.splitTextToSize(scan.command, contentWidth - 20);
  const cmdHeight = cmdLines.length * 5 + 15;
  doc.roundedRect(margin, yPos, contentWidth, cmdHeight, 3, 3, 'F');
  
  doc.setTextColor(200, 200, 200);
  doc.setFontSize(9);
  doc.setFont('courier', 'normal');
  doc.text('$', margin + 8, yPos + 12);
  doc.text(cmdLines, margin + 18, yPos + 12);
  
  yPos += cmdHeight + 15;

  // Output Section
  doc.setTextColor(0, 255, 150);
  doc.setFontSize(12);
  doc.setFont('helvetica', 'bold');
  doc.text('SCAN OUTPUT', margin, yPos);
  
  yPos += 10;

  // Process output
  doc.setTextColor(200, 200, 200);
  doc.setFontSize(8);
  doc.setFont('courier', 'normal');
  
  const lines = scan.output.split('\n');
  const maxCharsPerLine = 95;
  
  for (const line of lines) {
    // Check if we need a new page
    if (yPos > doc.internal.pageSize.getHeight() - 30) {
      doc.addPage();
      yPos = margin;
      
      // Add header on new page
      doc.setFillColor(17, 24, 39);
      doc.rect(0, 0, pageWidth, 20, 'F');
      doc.setTextColor(0, 255, 150);
      doc.setFontSize(10);
      doc.text('PENTEST REPORT (continued)', margin, 14);
      yPos = 35;
      
      doc.setTextColor(200, 200, 200);
      doc.setFontSize(8);
      doc.setFont('courier', 'normal');
    }
    
    // Color code based on content
    if (line.includes('[+]') || line.includes('FOUND') || line.includes('open')) {
      doc.setTextColor(0, 255, 150);
    } else if (line.includes('[!]') || line.includes('WARNING') || line.includes('VULN')) {
      doc.setTextColor(255, 200, 0);
    } else if (line.includes('[-]') || line.includes('ERROR') || line.includes('CRITICAL')) {
      doc.setTextColor(255, 100, 100);
    } else if (line.includes('[*]') || line.startsWith('>>>')) {
      doc.setTextColor(100, 200, 255);
    } else {
      doc.setTextColor(180, 180, 180);
    }
    
    // Wrap long lines
    if (line.length > maxCharsPerLine) {
      const wrappedLines = doc.splitTextToSize(line, contentWidth - 10);
      for (const wrappedLine of wrappedLines) {
        doc.text(wrappedLine, margin + 5, yPos);
        yPos += 4;
      }
    } else {
      doc.text(line || ' ', margin + 5, yPos);
      yPos += 4;
    }
  }

  // Footer
  const pageCount = doc.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFillColor(17, 24, 39);
    doc.rect(0, doc.internal.pageSize.getHeight() - 15, pageWidth, 15, 'F');
    
    doc.setTextColor(100, 100, 100);
    doc.setFontSize(8);
    doc.setFont('helvetica', 'normal');
    doc.text(
      `Generated by PenTest Command Center | Page ${i} of ${pageCount}`,
      pageWidth / 2,
      doc.internal.pageSize.getHeight() - 6,
      { align: 'center' }
    );
  }

  // Save the PDF
  const fileName = `pentest-${scan.toolName.toLowerCase()}-${format(new Date(scan.timestamp), 'yyyy-MM-dd-HHmm')}.pdf`;
  doc.save(fileName);
}