import { PentestTool } from './pentestTools';

const simulatedOutputs: Record<string, (target: string, values: Record<string, any>) => string[]> = {
  nmap: (target, values) => [
    `Starting Nmap 7.94 ( https://nmap.org )`,
    `Nmap scan report for ${target}`,
    `Host is up (0.0045s latency).`,
    ``,
    `PORT     STATE    SERVICE      VERSION`,
    `22/tcp   open     ssh          OpenSSH 8.9p1`,
    `80/tcp   open     http         nginx 1.24.0`,
    `443/tcp  open     https        nginx 1.24.0`,
    `3306/tcp filtered mysql`,
    `8080/tcp open     http-proxy   Apache Tomcat`,
    ``,
    `[+] Host appears to be running Linux (97% confidence)`,
    `[*] Service detection performed`,
    ``,
    `Nmap done: 1 IP address (1 host up) scanned`,
  ],
  
  sqlmap: (target, values) => [
    `        ___`,
    `       __H__`,
    ` ___ ___[)]_____ ___ ___  {1.7.12#stable}`,
    `|_ -| . ["]     | .'| . |`,
    `|___|_  [']_|_|_|__,|  _|`,
    `      |_|V...       |_|   https://sqlmap.org`,
    ``,
    `[*] starting @ ${new Date().toTimeString().split(' ')[0]}`,
    ``,
    `[*] testing connection to the target URL`,
    `[*] checking if the target is protected by some kind of WAF/IPS`,
    `[+] heuristics detected web page charset 'UTF-8'`,
    `[*] testing for SQL injection on GET parameter 'id'`,
    ``,
    `[+] GET parameter 'id' appears to be 'AND boolean-based blind' injectable`,
    `[+] GET parameter 'id' appears to be 'MySQL >= 5.0 error-based' injectable`,
    ``,
    `[!] VULNERABILITY FOUND: SQL Injection`,
    `    Parameter: id (GET)`,
    `    Type: boolean-based blind`,
    `    Payload: id=1' AND 8472=8472 AND 'aYKk'='aYKk`,
    ``,
    values.dbs ? `[*] fetching database names\navailable databases [3]:\n[*] information_schema\n[*] mysql\n[*] target_db` : '',
  ],
  
  nikto: (target, values) => [
    `- Nikto v2.5.0`,
    `---------------------------------------------------------------------------`,
    `+ Target IP:          ${target}`,
    `+ Target Hostname:    ${target}`,
    `+ Target Port:        ${values.port || 80}`,
    `+ Start Time:         ${new Date().toISOString()}`,
    `---------------------------------------------------------------------------`,
    `+ Server: nginx/1.24.0`,
    `+ /: The anti-clickjacking X-Frame-Options header is not present.`,
    `+ /: The X-Content-Type-Options header is not set.`,
    ``,
    `[+] OSVDB-3092: /admin/: This might be interesting.`,
    `[+] OSVDB-3268: /backup/: Directory indexing found.`,
    `[!] VULN: /config.php.bak: Backup file found containing sensitive info`,
    `[!] VULN: /.git/: Git repository found - source code exposure`,
    ``,
    `+ ${Math.floor(Math.random() * 50) + 20} requests: 0 error(s)`,
    `+ End Time: ${new Date().toISOString()}`,
  ],
  
  dirb: (target, values) => [
    `-----------------`,
    `DIRB v2.22`,
    `By The Dark Raver`,
    `-----------------`,
    ``,
    `START_TIME: ${new Date().toISOString()}`,
    `URL_BASE: ${target}/`,
    `WORDLIST_FILES: ${values.wordlist}`,
    ``,
    `-----------------`,
    ``,
    `GENERATED WORDS: 4612`,
    ``,
    `---- Scanning URL: ${target}/ ----`,
    `[+] FOUND: ${target}/admin (CODE:301|SIZE:169)`,
    `[+] FOUND: ${target}/api (CODE:200|SIZE:2341)`,
    `[+] FOUND: ${target}/backup (CODE:403|SIZE:276)`,
    `[+] FOUND: ${target}/config (CODE:301|SIZE:169)`,
    `[+] FOUND: ${target}/css (CODE:301|SIZE:169)`,
    `[+] FOUND: ${target}/images (CODE:301|SIZE:169)`,
    `[+] FOUND: ${target}/js (CODE:301|SIZE:169)`,
    `[+] FOUND: ${target}/login (CODE:200|SIZE:4521)`,
    `[+] FOUND: ${target}/uploads (CODE:403|SIZE:276)`,
    ``,
    `-----------------`,
    `END_TIME: ${new Date().toISOString()}`,
    `DOWNLOADED: 4612 - FOUND: 9`,
  ],
  
  hydra: (target, values) => [
    `Hydra v9.5 (c) 2023 by van Hauser/THC`,
    ``,
    `[DATA] max ${values.threads || 16} tasks per 1 server`,
    `[DATA] attacking ${values.service}://${target}`,
    `[STATUS] 156 tries in 00:00:45, remaining: 844`,
    ``,
    `[22][${values.service}] host: ${target}   login: admin   password: admin123`,
    `[22][${values.service}] host: ${target}   login: root    password: toor`,
    ``,
    `[!] CREDENTIALS FOUND:`,
    `    Username: admin`,
    `    Password: admin123`,
    ``,
    `1 of 1 target successfully completed, 2 valid passwords found`,
  ],
  
  wpscan: (target, values) => [
    `_______________________________________________________________`,
    `         __          _______   _____`,
    `         \\ \\        / /  __ \\ / ____|`,
    `          \\ \\  /\\  / /| |__) | (___   ___  __ _ _ __ ®`,
    `           \\ \\/  \\/ / |  ___/ \\___ \\ / __|/ _\` | '_ \\`,
    `            \\  /\\  /  | |     ____) | (__| (_| | | | |`,
    `             \\/  \\/   |_|    |_____/ \\___|\\__,_|_| |_|`,
    ``,
    `         WordPress Security Scanner by the WPScan Team`,
    `_______________________________________________________________`,
    ``,
    `[+] URL: ${target}/`,
    `[+] Started: ${new Date().toISOString()}`,
    ``,
    `[+] WordPress version 6.4.2 identified`,
    `[+] WordPress theme in use: flavor`,
    ``,
    `[!] VULN: WordPress < 6.4.3 - Admin+ Arbitrary File Upload`,
    `    Fixed in: 6.4.3`,
    `    Reference: https://wpscan.com/vulnerability/xxx`,
    ``,
    `[+] Enumerating ${values.enumerate === 'vp' ? 'Vulnerable Plugins' : values.enumerate}...`,
    ``,
    `[!] VULN: contact-form-7 < 5.8.4 - XSS Vulnerability`,
    `[!] VULN: elementor < 3.18.2 - Auth Bypass`,
    `[+] yoast-seo - No known vulnerabilities`,
  ],
  
  nuclei: (target, values) => [
    `                     __     _`,
    `   ____  __  _______/ /__  (_)`,
    `  / __ \\/ / / / ___/ / _ \\/ /`,
    ` / / / / /_/ / /__/ /  __/ /`,
    `/_/ /_/\\__,_/\\___/_/\\___/_/   v3.1.0`,
    ``,
    `[INF] Running nuclei with ${values.templates} templates`,
    `[INF] Targets loaded: 1`,
    ``,
    `[CVE-2023-44487] [http] [critical] ${target}`,
    `[CVE-2023-46747] [http] [high] ${target}`,
    `[git-config] [http] [medium] ${target}/.git/config`,
    `[robots-txt] [http] [info] ${target}/robots.txt`,
    `[security-txt] [http] [info] ${target}/.well-known/security.txt`,
    ``,
    `[!] CRITICAL: HTTP/2 Rapid Reset Attack (CVE-2023-44487)`,
    `[!] HIGH: F5 BIG-IP Auth Bypass (CVE-2023-46747)`,
    ``,
    `[INF] Found 5 results in ${(Math.random() * 30 + 10).toFixed(2)}s`,
  ],
  
  gobuster: (target, values) => [
    `===============================================================`,
    `Gobuster v3.6`,
    `by OJ Reeves (@TheColonial) & Christian Mehlmauer (@firefart)`,
    `===============================================================`,
    `[+] Url:                     ${target}`,
    `[+] Method:                  GET`,
    `[+] Threads:                 ${values.threads || 10}`,
    `[+] Wordlist:                ${values.wordlist}`,
    `[+] Status codes:            200,204,301,302,307,401,403,405`,
    `===============================================================`,
    `Starting gobuster in ${values.mode} enumeration mode`,
    `===============================================================`,
    `/admin                (Status: 301) [Size: 169]`,
    `/api                  (Status: 200) [Size: 2451]`,
    `/assets               (Status: 301) [Size: 169]`,
    `/backup               (Status: 403) [Size: 276]`,
    `/config               (Status: 403) [Size: 276]`,
    `/dashboard            (Status: 302) [Size: 0] --> /login`,
    `/docs                 (Status: 200) [Size: 8923]`,
    `/health               (Status: 200) [Size: 15]`,
    `/static               (Status: 301) [Size: 169]`,
    `/uploads              (Status: 403) [Size: 276]`,
    `===============================================================`,
    `Finished`,
  ],
  
  subfinder: (target, values) => [
    `               __    _____           __         `,
    `   _______  __/ /_  / __(_)___  ____/ /__  _____`,
    `  / ___/ / / / __ \\/ /_/ / __ \\/ __  / _ \\/ ___/`,
    ` (__  ) /_/ / /_/ / __/ / / / / /_/ /  __/ /    `,
    `/____/\\__,_/_.___/_/ /_/_/ /_/\\__,_/\\___/_/  v2.6.3`,
    ``,
    `[INF] Enumerating subdomains for ${target}`,
    ``,
    `www.${target}`,
    `api.${target}`,
    `mail.${target}`,
    `admin.${target}`,
    `dev.${target}`,
    `staging.${target}`,
    `cdn.${target}`,
    `blog.${target}`,
    `shop.${target}`,
    `app.${target}`,
    `portal.${target}`,
    `test.${target}`,
    ``,
    `[INF] Found 12 subdomains for ${target} in ${(Math.random() * 10 + 5).toFixed(0)}s`,
  ],
  
  whatweb: (target, values) => [
    `WhatWeb report for ${target}`,
    `Status: 200 OK`,
    ``,
    `[+] Country: UNITED STATES`,
    `[+] IP: 104.21.xxx.xxx`,
    ``,
    `[+] Detected Technologies:`,
    `    HTTP Server: nginx/1.24.0`,
    `    JavaScript Framework: React 18.2.0`,
    `    CSS Framework: Tailwind CSS 3.4.0`,
    `    CMS: WordPress 6.4.2`,
    `    Programming Language: PHP 8.2`,
    `    Database: MySQL`,
    ``,
    `[+] Security Headers:`,
    `    X-Frame-Options: SAMEORIGIN`,
    `    X-XSS-Protection: 1; mode=block`,
    `    [!] Missing: Content-Security-Policy`,
    `    [!] Missing: Strict-Transport-Security`,
  ],
  
  masscan: (target, values) => [
    `Starting masscan ${new Date().toISOString()}`,
    `Initiating SYN Stealth Scan`,
    `Scanning ${target} [${values.ports || '1-1000'}]`,
    `Rate: ${values.rate || 1000}.00 pps`,
    ``,
    `Discovered open port 22/tcp on ${target}`,
    `Discovered open port 80/tcp on ${target}`,
    `Discovered open port 443/tcp on ${target}`,
    `Discovered open port 3306/tcp on ${target}`,
    `Discovered open port 8080/tcp on ${target}`,
    `Discovered open port 8443/tcp on ${target}`,
    ``,
    values.banners ? `Banner on 80/tcp: HTTP/1.1 200 OK\\r\\nServer: nginx/1.24.0` : '',
    ``,
    `Masscan done: 1 IP address (6 ports) scanned in ${(Math.random() * 5 + 2).toFixed(2)}s`,
  ],
  
  ffuf: (target, values) => [
    `        /'___\\  /'___\\           /'___\\       `,
    `       /\\ \\__/ /\\ \\__/  __  __  /\\ \\__/       `,
    `       \\ \\ ,__\\\\ \\ ,__\\/\\ \\/\\ \\ \\ \\ ,__\\      `,
    `        \\ \\ \\_/ \\ \\ \\_/\\ \\ \\_\\ \\ \\ \\ \\_/      `,
    `         \\ \\_\\   \\ \\_\\  \\ \\____/  \\ \\_\\       `,
    `          \\/_/    \\/_/   \\/___/    \\/_/       `,
    ``,
    `       v2.1.0`,
    `________________________________________________`,
    ``,
    ` :: Method           : ${values.method || 'GET'}`,
    ` :: URL              : ${target}`,
    ` :: Wordlist         : ${values.wordlist}`,
    ` :: Threads          : ${values.threads || 40}`,
    `________________________________________________`,
    ``,
    `admin                   [Status: 200, Size: 4523]`,
    `api                     [Status: 200, Size: 156]`,
    `assets                  [Status: 301, Size: 169]`,
    `backup                  [Status: 403, Size: 276]`,
    `config.old              [Status: 200, Size: 892]`,
    `dashboard               [Status: 302, Size: 0]`,
    `login                   [Status: 200, Size: 2341]`,
    `phpinfo                 [Status: 200, Size: 68432]`,
    ``,
    `:: Progress: [4614/4614] :: Errors: 0 ::`,
  ],
  
  dnsenum: (target, values) => [
    `dnsenum VERSION:1.2.6`,
    ``,
    `----- ${target} -----`,
    ``,
    `Host's addresses:`,
    `__________________`,
    `${target}.                  300     IN    A    104.21.xxx.xxx`,
    `${target}.                  300     IN    A    172.67.xxx.xxx`,
    ``,
    `Name Servers:`,
    `______________`,
    `ns1.${target}.              86400   IN    A    173.245.58.xxx`,
    `ns2.${target}.              86400   IN    A    173.245.59.xxx`,
    ``,
    `Mail (MX) Servers:`,
    `___________________`,
    `mail.${target}.             300     IN    A    104.21.xxx.xxx`,
    ``,
    values.whois ? `Whois Information:\n  Registrar: Cloudflare, Inc.\n  Creation Date: 2020-01-15\n  Expiry Date: 2025-01-15` : '',
    ``,
    `Brute forcing with dns.txt:`,
    `___________________________`,
    `www.${target}.              300     IN    A    104.21.xxx.xxx`,
    `api.${target}.              300     IN    A    104.21.xxx.xxx`,
    `mail.${target}.             300     IN    A    104.21.xxx.xxx`,
  ],
  
  theharvester: (target, values) => [
    `*******************************************************************`,
    `*  _   _                                            _             *`,
    `* | |_| |__   ___    /\\  /\\__ _ _ ____   _____  ___| |_ ___ _ __  *`,
    `* | __| '_ \\ / _ \\  / /_/ / _\` | '__\\ \\ / / _ \\/ __| __/ _ \\ '__| *`,
    `* | |_| | | |  __/ / __  / (_| | |   \\ V /  __/\\__ \\ ||  __/ |    *`,
    `*  \\__|_| |_|\\___| \\/ /_/ \\__,_|_|    \\_/ \\___||___/\\__\\___|_|    *`,
    `*                                                                 *`,
    `* theHarvester 4.4.4                                              *`,
    `*******************************************************************`,
    ``,
    `[*] Target: ${target}`,
    `[*] Searching ${values.source || 'all'} for domain ${target}`,
    ``,
    `[+] Emails found:`,
    `    admin@${target}`,
    `    info@${target}`,
    `    support@${target}`,
    `    contact@${target}`,
    `    sales@${target}`,
    ``,
    `[+] Hosts found:`,
    `    www.${target}:104.21.xxx.xxx`,
    `    api.${target}:104.21.xxx.xxx`,
    `    mail.${target}:104.21.xxx.xxx`,
    ``,
    `[+] IPs found: 3`,
    `[+] Emails found: 5`,
    `[+] Hosts found: 3`,
  ],
  
  amass: (target, values) => [
    `        .+++:.            :                             .+++.`,
    `      +W@@@@@8        &+W@#               o8teleW+   +W@@@@@W#702`,
    `     +@@@@@@@@@@@@@@@@@@@@@@W            @@@@@@@@@@@@@@@@@@@@@@@@#`,
    ``,
    `                                   https://github.com/owasp-amass/amass`,
    `                                             v4.2.0`,
    ``,
    `[INF] Starting ${values.mode || 'enum'} enumeration`,
    `[INF] Target: ${target}`,
    values.passive ? '[INF] Running in passive mode' : '[INF] Running in active mode',
    ``,
    `[+] www.${target}`,
    `[+] api.${target}`,
    `[+] mail.${target}`,
    `[+] admin.${target}`,
    `[+] dev.${target}`,
    `[+] staging.${target}`,
    `[+] cdn.${target}`,
    `[+] app.${target}`,
    `[+] portal.${target}`,
    `[+] internal.${target}`,
    ``,
    `[INF] OWASP Amass finished: 10 assets found`,
    `[INF] Duration: ${values.timeout || 30}m`,
  ],
};

export async function simulateScan(
  tool: PentestTool,
  values: Record<string, any>,
  onOutput: (line: string) => void
): Promise<void> {
  const target = values.target || values.url || values.host || values.domain || 'target.com';
  const outputGenerator = simulatedOutputs[tool.id];
  
  if (!outputGenerator) {
    onOutput(`[*] Starting ${tool.name} scan...`);
    onOutput(`[*] Target: ${target}`);
    await delay(1000);
    onOutput(`[+] Scan initiated`);
    await delay(2000);
    onOutput(`[+] Scan completed successfully`);
    return;
  }
  
  const lines = outputGenerator(target, values).filter(Boolean);
  
  for (const line of lines) {
    await delay(Math.random() * 200 + 50);
    onOutput(line);
  }
}

function delay(ms: number): Promise<void> {
  return new Promise((resolve) => setTimeout(resolve, ms));
}